plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.144'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    maven { url = 'https://repo.u-team.info' }
    maven { url = 'https://maven.arbjerg.dev/releases' }
    maven {
        url = 'https://maven.lavalink.dev/snapshots'
        mavenContent { snapshotsOnly() }
    }
    mavenCentral()
}

neoForge {
    version = project.neo_version

    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    def lava = implementation('net.hycrafthd.lavaplayer:lavaplayer:2.2.4-fix-j8')
    jarJar(lava) {
        version {
            strictly '[2.2.4-fix-j8]'
            prefer '2.2.4-fix-j8'
        }
    }

    def yt = implementation('dev.lavalink.youtube:v2:c46ab888ee12bc4bcb37c8ebcaf180e85ae30368-SNAPSHOT')
    jarJar(yt) {
        version {
            strictly '[c46ab888ee12bc4bcb37c8ebcaf180e85ae30368-SNAPSHOT]'
            prefer 'c46ab888ee12bc4bcb37c8ebcaf180e85ae30368-SNAPSHOT'
        }
    }

    additionalRuntimeClasspath 'net.hycrafthd.lavaplayer:lavaplayer:2.2.4-fix-j8'
    additionalRuntimeClasspath 'dev.lavalink.youtube:v2:c46ab888ee12bc4bcb37c8ebcaf180e85ae30368-SNAPSHOT'
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
        minecraft_version_range: minecraft_version_range,
        neo_version_range: neo_version_range,
        loader_version_range: loader_version_range,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_version: mod_version,
        mod_authors: mod_authors,
        mod_description: mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
