org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.248
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=vinyl_music
mod_name=Vinyl Music
mod_license=MIT
mod_version=0.1.0-alpha.1
mod_group_id=dev.vinylmusic
mod_authors=ivanleopoldo
mod_description=A standalone streaming vinyl, album, playlist import, record press, and record player mod.
